let animals = ["Dog", "Cat", "Rat"];
console.log(animals);
animals.push("Fish");
console.log(animals);
animals.unshift("Horse");
console.log(animals);
animals.push("Giraffe", "Snake");
console.log(animals);
animals.shift();
console.log(animals);
animals.pop();
console.log(animals);
animals.shift();
console.log(animals);
console.log(animals.length);
